<!-- resources/views/admin/invoices/custom-manage.blade.php -->

@extends('admin.layouts.admin-layout')

@section('title', 'Manage Custom Invoices')

@section('content')
<div class="container mt-5">
    <div class="card shadow-sm">
        <div class="card-body">
            <h4 class="fw-bold">Manage Custom Invoices</h4>
            <p>All custom invoices in the system. You can search, filter, and paginate the results.</p>
            <!-- DataTable -->
            <div class="table-responsive">
            <table id="custom-invoices-table" class="table table-striped table-bordered dt-responsive nowrap" style="width:100%">
                <thead>
                    <tr>
                        <th>S/N</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Service Type</th>
                        <th>Invoice Number</th>
                        <th>Amount</th>
                        <th>Issue Date</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <!-- Data will be fetched via AJAX -->
                </tbody>
            </table>

            </div>
        </div>
    </div>
</div>
<!-- Delete Confirmation Modal -->
<div class="modal fade" id="deleteInvoiceModal" tabindex="-1" aria-labelledby="deleteInvoiceModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteInvoiceModalLabel">Confirm Delete</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this custom invoice?</p>
                <p>This action cannot be undone.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-danger" id="confirm-delete">
                    <span id="delete-btn-text">Delete</span>
                    <span id="delete-btn-spinner" class="spinner-border spinner-border-sm" style="display: none;" role="status" aria-hidden="true"></span>
                </button>
            </div>
        </div>
    </div>
</div>

@endsection

@push('scripts')
<script>
$(document).ready(function() {
    let table = $('#custom-invoices-table').DataTable({
        responsive: true,
        processing: true,
        serverSide: true,
        ajax: {
            url: "{{ route('admin.customInvoices.fetch') }}",
            method: 'GET',
            dataSrc: 'data',
            error: function(xhr, status, error) {
                console.error('DataTables AJAX error:', error);
            }
        },
        columns: [
            { data: null }, // S/N will be generated by DataTable
            { data: 'name' },
            { data: 'email' },
            { data: 'service_type' },
            { data: 'invoice_number' },
            { data: 'amount' },
            { data: 'issue_date' },
            { data: 'status', render: function(data) {
                if (data === 'Paid') return '<span class="badge bg-success">Paid</span>';
                if (data === 'Unpaid') return '<span class="badge bg-danger">Unpaid</span>';
                if (data === 'Refunded') return '<span class="badge bg-info">Refunded</span>';
                return '<span class="badge bg-secondary">Unknown</span>';
            }},
            { data: null, render: function(data) {
                return `
                    <a href="/admin/custom-invoices/${data.id}/view" class="btn btn-sm btn-info">View</a>
                    <a href="/admin/custom-invoices/${data.id}/edit" class="btn btn-sm btn-warning">Edit</a>
                    <button class="btn btn-sm btn-danger" onclick="confirmDelete(${data.id})">Delete</button>
                `;
            }},
        ],
        drawCallback: function(settings) {
            let api = this.api();
            let startIndex = api.page.info().start;
            api.column(0, { page: 'current' }).nodes().each(function(cell, i) {
                cell.innerHTML = startIndex + i + 1;
            });
        }
    });

    // Delete confirmation modal function
    window.confirmDelete = function(id) {
        $('#deleteInvoiceModal').modal('show'); // Show the modal
        $('#confirm-delete').off('click').on('click', function() { // Set up the deletion function
            deleteCustomInvoice(id);
        });
    }

    // Delete custom invoice function
    function deleteCustomInvoice(id) {
        const btnText = $('#delete-btn-text');
        const btnSpinner = $('#delete-btn-spinner');
        
        btnText.hide();
        btnSpinner.show();

        $.ajax({
            url: `/admin/custom-invoices/${id}/delete`, // Updated URL to include 'admin' prefix
            method: 'DELETE',
            headers: { 'X-CSRF-TOKEN': '{{ csrf_token() }}' },
            success: function(response) {
                $('#deleteInvoiceModal').modal('hide');
                btnText.show();
                btnSpinner.hide();
                table.ajax.reload(); // Refresh the DataTable
                alert('Custom invoice deleted successfully.');
            },
            error: function(xhr, status, error) {
                btnText.show();
                btnSpinner.hide();
                console.error('Error deleting custom invoice:', error);
                alert('Failed to delete custom invoice.');
            }
        });
    }
});

</script>
@endpush
